### ISSUE TITLE
Requirements Document

### ISSUE THREAD

**Issue by ztg6893** [bjpicciano/SWEN-344-Bookstore#1]
**Due September 26**
Need clarification from professor on some of the requirements

**Comment by ztg6893** [comment]
At least 10 use cases

**Comment by bjpicciano** [comment]
At least 10 use cases
[Include wireframes for all pages your team is responsible for](https://en.wikipedia.org/wiki/Website_wireframe)
At least 5 projects risks - with a 1-2 paragraph write up (for each risk) of how you plan to address these risks
At least 15 good user stories
